writer1 = console
writer1.format = {date: yyyy-MM-dd HH:mm:ss} [{thread}] {level}: {class}.{method}() - {message}

writer2 = rolling file
writer2.file = logs/application_{date:yyyy-MM-dd_HH-mm-ss}.log
writer2.latest = logs/latest.log
writer2.format = {date: yyyy-MM-dd HH:mm:ss} [{thread}] {level}: {class}.{method}() - {message}
writer2.policies = startup